### ISSUE TITLE
pycsw image enhancements

### ISSUE THREAD

**Issue by ricardogsilva** [geocontainers/dockerfiles#11]
The current image for `pycsw` has some limitations that (IMHO) prevent using it in production systems:

- It uses pycsw's master branch directly. This makes it hard to generate reproducible environments. Alternatively one could fetch only tagged versions
- It only features support for the `sqlite` backend. Alternatively, dependencies for other backends could be provided

I am willing to work on this image in order to provide a more flexible setup.

**Comment by ricardogsilva** [comment]
Closing this as it is perhaps not relevant anymore. We've added an official pycsw docker image to [dockerhub](https://hub.docker.com/r/geopython/pycsw/).

**Comment by nuest** [comment]
Thanks for the update. The most important thing is the image is maintained by you and on the Hub!
